spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
    alicloud:
      access-key: LTAI5tFtV5wzFJKhv9Z9RQsH
      secret-key: jmKvKfNPgdVh3op9S7wcIwdNr9rxHy
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: yjmall-file

  application:
    name: yjmall-third-party

server:
  port: 30000
